name: Makefile CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: initialize
      run: |
        sudo apt-get install wget make python3 python3-pip
        python3 -m pip install -r requirements.txt    
    - name: download inputs
      run: bash wgetdata.sh      
    - name: CHEBI
      run: mv database_accession_3star.tsv CHEBI && cd CHEBI && python CHEBI.py
    - name: bigg.metabolite
      run: mv bigg_models_metabolites.txt bigg.metabolite && cd bigg.metabolite && python bigg.metabolite.py
    - name: bigg.reaction
      run: mv bigg_models_reactions.txt bigg.reaction && cd bigg.reaction && python bigg.reaction.py
    - name: brenda
      run: cd brenda && tar xf brenda_2022_2.json.tar.gz && python brnda.py
