name: Makefile CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: initialize
      run: |
        sudo apt-get install wget make python3 python3-pip
        python3 -m pip install -r requirements.txt
    
    - name: download inputs
      run: cd scripts && bash download.sh
      
    - name: make bigg.metabolite.csv
      run: make bigg.metabolite.csv
      
